### ISSUE TITLE
What do we need to enter in Enter License Data?

### ISSUE THREAD

**Issue by hrz0x** [dhavalhariyani/hs-widevine#1]
Is it license url? I entered it and it says 

Getting Keys...
unable to parse license - check protobufs

**Comment by Puyodead1** [comment]
Not sure if its the same for you, but for me it was because the returned base64 was an error not an actual license response

**Comment by dhavalhariyani** [comment]
Yes, you need to parse the license URL which you get from the hs

**Comment by hrz0x** [comment]
Does this still work?

**Comment by dhavalhariyani** [comment]
L3 Chrome CDM dead, project is discontinued till new CDM arrives
