### ISSUE TITLE
CDM L3 LEAKED

### ISSUE THREAD

**Issue by SurrenderS12** [dhavalhariyani/hs-widevine#5]
Android_general_L3.zip[Android general L3](https://anonfiles.com/pd5en6666e52u9/android_general_zip)

**Comment by SurrenderS12** [comment]
Happy ripping bitches

**Comment by SurrenderS12** [comment]
Password FUCKED99

**Comment by etnaddcok** [comment]
how is this used?

**Comment by etnaddcok** [comment]
> Password FUCKED99

Could you put screenshots of how it is used?

**Comment by saidekrishna** [comment]
> Android_general_L3.zip[Android general L3](https://anonfiles.com/pd5en6666e52u9/android_general_zip)

The file you are looking for could not be found

**Comment by dhavalhariyani** [comment]
> Android_general_L3.zip[Android general L3](https://anonfiles.com/pd5en6666e52u9/android_general_zip)

Hey dude, can you share this again? Because it's deleted ig. You can send this to me or post here. I'd update the code.

**Comment by loveyoursupport** [comment]
Stop sharing a revoked key , Share L1 if you dare

**Comment by dhavalhariyani** [comment]
> Share L1 if you dare

bro 😂, please be kind for whatever he's giving.

**Comment by loveyoursupport** [comment]
It is already revoked but some small sites are using it so he is sharing for killing it , so share if you have L1 @SurrenderS12  because some L1s leaked samsung and OnePlus + Chrome 2209 , so share if you dare

**Comment by rvanik** [comment]
That's right, it's been revoked. Especially Netflix and similar don't accept this already. In this script, it will also no longer work. Already a crowd of people have killed like the last nexus l1 and similar.So here only a new key is NEEDED NOW.

**Comment by dhavalhariyani** [comment]
alright, if anyone gets a new and working CDM that actually work with this script then please contribute.

**Comment by detodotv** [comment]
> Happy ripping bitches

hello bro, question, how do you get it? thanks!

**Comment by astravaganza** [comment]
https://github.com/astravaganza/android_general
