### ISSUE TITLE
New Cdm   aka  NoDRM widevine-l3-guesser

### ISSUE THREAD

**Issue by 2borbar2b2** [dhavalhariyani/hs-widevine#6]
Update: **Chrome CDM dead, project is discontinued till new CDM arrives** .....

https://github.com/Satsuoni/widevine-l3-guesser

**Comment by MG577** [comment]
@2borbar2b2 it has no CDM inside .. Only public key .. No private key inside content_key_decryption.js

**Comment by dhavalhariyani** [comment]
It is not CDM, it's just a script that gives a key from your own device.
